# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        echo "Creating the Service Connection"
        ServiceConnection=$(az devops service-endpoint create --service-endpoint-configuration ./Configuration.json --organization https://dev.azure.com/v-jeaustinro --project JeaustinProject)
        ServiceConnectionID=$(echo $ServiceConnection | jq -r '.id')
        echo "Service Connection ID: $ServiceConnectionID"
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

